version: '2'

services:
  styleguide:
    build: .
    command: tail -F /var/log/dmesg
    volumes:
      # - ./app:/wetravel
      - C:\Users\75650\Desktop\wetravel\styleguide-sinatra:/styleguide
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      app_net:
        ipv4_address: 172.16.1.2
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1
